### ISSUE TITLE
Where to get the models from?

### ISSUE THREAD

**Issue by adroit91** [drakelevy/FSRCNN-TensorFlow#1]
Hi, great job there!
Could you please let me know where to get the pre-trained models from in order to replicate your results on grayscale?
Would also like to help with converting to 3-channel images.

**Comment by drakelevy** [comment]
Hey, there actually aren't any pre-trained models. You'll have to train the network yourself, which you can do with the Train images provided. I'll think about releasing a pre-trained model though.

Sounds good! Feel free to fork the repo and make some changes. You should just have to change the depth of the network input/output layers to 3 and in preprocessing open the images as RGB instead of 8-bit BW.

**Comment by haasn** [comment]
If you could release a pre-trained model, that would be great for people trying to implement this, since it gives a set of reference data to test with without having to spend forever training your own network.
